// Verifies the JS BPE port produces byte-for-byte identical tokens/ids to
// the real Python `tokenizers` library, for a given tokenizer.json + a
// reference file generated by generate_reference.py.
//
// Usage: node test/compare_with_python.js [tokenizer.json path] [reference.json path]
// Defaults to v1's tokenizer + reference if no args given.
const fs = require("fs");
const path = require("path");
const { BPETokenizer } = require("../tokenizer.js");

const tokenizerPath = process.argv[2]
  ? path.resolve(process.argv[2])
  : path.join(__dirname, "..", "models", "v1", "tokenizer.json");
const referencePath = process.argv[3]
  ? path.resolve(process.argv[3])
  : path.join(__dirname, "reference_v1.json");

const tok = new BPETokenizer(JSON.parse(fs.readFileSync(tokenizerPath, "utf-8")));
const reference = JSON.parse(fs.readFileSync(referencePath, "utf-8"));

console.log(`Tokenizer: ${tokenizerPath}`);
console.log(`Reference: ${referencePath}\n`);

let failures = 0;
for (const { text, tokens: pyTokens, ids: pyIds } of reference) {
  const { atoms } = tok.tokenize(text);
  // Pieces with id===null mean "dropped" (v1's unk_token=None behavior --
  // verified against Python: unrecognized chars produce zero output, not a
  // placeholder). This filter is a no-op for tokenizers with a real
  // unk_token (e.g. v2's "[UNK]"), since encodeAtom never returns id:null
  // in that case -- so the same comparison logic works for both pipelines.
  const valid = atoms.flatMap((a) => a.pieces.filter((p) => p.id !== null));
  const jsPieces = valid.map((p) => p.piece);
  const jsIds = valid.map((p) => p.id);

  const tokensMatch = JSON.stringify(jsPieces) === JSON.stringify(pyTokens);
  const idsMatch = JSON.stringify(jsIds) === JSON.stringify(pyIds);

  if (tokensMatch && idsMatch) {
    console.log(`OK   ${JSON.stringify(text)} -> ${jsPieces.length} tokens`);
  } else {
    failures++;
    console.log(`FAIL ${JSON.stringify(text)}`);
    if (!tokensMatch) {
      console.log(`  py tokens: ${JSON.stringify(pyTokens)}`);
      console.log(`  js tokens: ${JSON.stringify(jsPieces)}`);
    }
    if (!idsMatch) {
      console.log(`  py ids: ${JSON.stringify(pyIds)}`);
      console.log(`  js ids: ${JSON.stringify(jsIds)}`);
    }
  }
}

console.log(`\n${reference.length - failures}/${reference.length} passed`);
process.exit(failures > 0 ? 1 : 0);
