// Verifies the JS BPE port produces byte-for-byte identical tokens/ids to
// the real Python `tokenizers` library, using the same tokenizer.json.
// Reference cases generated by a one-off Python script into /tmp/py_reference.json.
const fs = require("fs");
const path = require("path");
const { BPETokenizer } = require("../tokenizer.js");

const tokenizerPath = path.join(__dirname, "..", "models", "v1", "tokenizer.json");
const tok = new BPETokenizer(JSON.parse(fs.readFileSync(tokenizerPath, "utf-8")));

const referencePath = "/tmp/py_reference.json";
const reference = JSON.parse(fs.readFileSync(referencePath, "utf-8"));

let failures = 0;
for (const { text, tokens: pyTokens, ids: pyIds } of reference) {
  const { atoms } = tok.tokenize(text);
  // Real HF behavior with unk_token=None: pieces with no vocab entry are
  // silently dropped from .tokens/.ids entirely (verified against Python --
  // e.g. "!" is absent from this vocab and produces zero output, not a
  // placeholder). Filter the same way here to compare apples to apples.
  const valid = atoms.flatMap((a) => a.pieces.filter((p) => p.id !== null));
  const jsPieces = valid.map((p) => p.piece);
  const jsIds = valid.map((p) => p.id);

  const tokensMatch = JSON.stringify(jsPieces) === JSON.stringify(pyTokens);
  const idsMatch = JSON.stringify(jsIds) === JSON.stringify(pyIds);

  if (tokensMatch && idsMatch) {
    console.log(`OK   "${text}" -> ${jsPieces.length} tokens`);
  } else {
    failures++;
    console.log(`FAIL "${text}"`);
    if (!tokensMatch) {
      console.log(`  py tokens: ${JSON.stringify(pyTokens)}`);
      console.log(`  js tokens: ${JSON.stringify(jsPieces)}`);
    }
    if (!idsMatch) {
      console.log(`  py ids: ${JSON.stringify(pyIds)}`);
      console.log(`  js ids: ${JSON.stringify(jsIds)}`);
    }
  }
}

console.log(`\n${reference.length - failures}/${reference.length} passed`);
process.exit(failures > 0 ? 1 : 0);
