// Verifies tokenizer.js's countFaithfulUnits() matches the real Python
// implementation (v2/faithful_units.py) exactly, using the reference file
// generated by generate_faithful_units_reference.py.
const fs = require("fs");
const path = require("path");
const { countFaithfulUnits } = require("../tokenizer.js");

const referencePath = path.join(__dirname, "reference_faithful_units.json");
const reference = JSON.parse(fs.readFileSync(referencePath, "utf-8"));

let failures = 0;
for (const { text, units: pyUnits } of reference) {
  const jsUnits = countFaithfulUnits(text);
  if (jsUnits === pyUnits) {
    console.log(`OK   ${JSON.stringify(text)} -> ${jsUnits} units`);
  } else {
    failures++;
    console.log(`FAIL ${JSON.stringify(text)}: py=${pyUnits} js=${jsUnits}`);
  }
}

console.log(`\n${reference.length - failures}/${reference.length} passed`);
process.exit(failures > 0 ? 1 : 0);
