"""Evidence Bundle: assembles the assignment's required PASS/FAIL table
from real, already-computed facts.

Per the assignment brief: "evidence.json must record whether every major
requirement passed and where the supporting evidence can be found... The
evidence bundle must be generated by the implementation. Hardcoded
evidence will not be accepted." This module enforces that boundary
structurally: it never computes anything itself, only assembles
`EvidenceRow`s the *caller* already derived from real results (a
`ResumeVerificationResult.matched`, a `ReplayResult.matched`, an actual
`ManifestStore` lookup, etc.) -- there is no code path here that could
silently hardcode "PASS" without a real check having produced it
upstream, which is exactly what scripts/run_demo.py's assembly step must
be able to point back to for every row.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple


@dataclass(frozen=True)
class EvidenceRow:
    requirement: str
    passed: bool
    evidence: str  # human-readable pointer to what was actually checked


def build_evidence_bundle(rows: List[EvidenceRow]) -> Tuple[dict, str]:
    """Returns (evidence.json's dict, evidence.md's text)."""
    evidence_json = {
        "requirements": [
            {"requirement": r.requirement, "result": "PASS" if r.passed else "FAIL", "evidence": r.evidence}
            for r in rows
        ],
        "overall": "PASS" if all(r.passed for r in rows) else "FAIL",
    }

    lines = ["# Evidence Bundle", "", "| Requirement | Result | Evidence |", "|---|---|---|"]
    for r in rows:
        lines.append(f"| {r.requirement} | {'PASS' if r.passed else 'FAIL'} | {r.evidence} |")
    lines.append("")
    lines.append(f"**Overall: {evidence_json['overall']}**")
    evidence_md = "\n".join(lines) + "\n"

    return evidence_json, evidence_md


def write_evidence_bundle(rows: List[EvidenceRow], json_path: str | Path, md_path: str | Path) -> dict:
    evidence_json, evidence_md = build_evidence_bundle(rows)
    Path(json_path).parent.mkdir(parents=True, exist_ok=True)
    with open(json_path, "w") as f:
        json.dump(evidence_json, f, indent=2)
    Path(md_path).parent.mkdir(parents=True, exist_ok=True)
    with open(md_path, "w") as f:
        f.write(evidence_md)
    return evidence_json
